/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./components/card.vue')['default']
    DynamicComponent: typeof import('./components/dynamicComponent.vue')['default']
    OverlayCallKing: typeof import('./components/overlayCallKing.vue')['default']
    OverlayGameType: typeof import('./components/overlayGameType.vue')['default']
    OverlayMisere: typeof import('./components/overlayMisere.vue')['default']
    OverlayPoignee: typeof import('./components/overlayPoignee.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
