/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/card.vue')['default']
    DynamicComponent: typeof import('./src/components/dynamicComponent.vue')['default']
    OverlayCallKing: typeof import('./src/components/overlayCallKing.vue')['default']
    OverlayGameType: typeof import('./src/components/overlayGameType.vue')['default']
    OverlayMakeChien: typeof import('./src/components/overlayMakeChien.vue')['default']
    OverlayMisereAtout: typeof import('./src/components/overlayMisereAtout.vue')['default']
    OverlayMisereFigure: typeof import('./src/components/overlayMisereFigure.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
