name: Node.js Package

on: push

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.6
      - run: yarn
      - run: yarn run build

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.6
          registry-url: https://npm.pkg.github.com/
      - name: Set deployment token
        run: yarn config set '//registry.npmjs.org/:_authToken' "${GITHUB_TOKEN}"
      - run: yarn
      - run: yarn publish
